// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Sumit Dhiman",
            "url": "https://sumitdhiman.live",
            "email": "sd08012003@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/user": {
            "get": {
                "description": "respond with json of user data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Current User"
                ],
                "summary": "Shows the current user logged in.",
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "description": "Login the user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Login view",
                "responses": {}
            }
        },
        "/register": {
            "post": {
                "description": "Responds with the Registeration of user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register"
                ],
                "summary": "Register The user",
                "responses": {}
            }
        },
        "/user/:id": {
            "get": {
                "description": "Responds with the user details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetUser"
                ],
                "summary": "Get the user with id",
                "responses": {}
            }
        },
        "/user/delete/:id": {
            "post": {
                "description": "Responds with the deletion of user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Delete"
                ],
                "summary": "Deletes The user with id",
                "responses": {}
            }
        },
        "/users": {
            "get": {
                "description": "Responds with the data of users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AllUser"
                ],
                "summary": "Return all users",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Blog app in Go",
	Description:      "A Blog app made to publish my blogs in Go using Gin framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
